In [477]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from xgboost import XGBRegressor, XGBClassifier

from sklearn.metrics import (r2_score, mean_squared_error,
                              accuracy_score, confusion_matrix,
                              classification_report, ConfusionMatrixDisplay)

In [478]:
df = pd.read_csv('car_price_prediction.csv')
df

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6,Automatic,4x4,4-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6,Tiptronic,4x4,4-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4,Variator,Front,4-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4,Automatic,4x4,4-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4,Automatic,Front,4-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,-,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000 km,4,Manual,Rear,2-Mar,Left wheel,Silver,5
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600 km,4,Tiptronic,Front,4-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365 km,4,Automatic,Front,4-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258 km,4,Automatic,Front,4-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923 km,4,Automatic,Front,4-May,Left wheel,White,12

In [479]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                19237 non-null  int64
 1   Price             19237 non-null  int64
 2   Levy              19237 non-null  str
 3   Manufacturer      19237 non-null  str
 4   Model             19237 non-null  str
 5   Prod. year        19237 non-null  int64
 6   Category          19237 non-null  str
 7   Leather interior  19237 non-null  str
 8   Fuel type         19237 non-null  str
 9   Engine volume     19237 non-null  str
 10  Mileage           19237 non-null  str
 11  Cylinders         19237 non-null  int64
 12  Gear box type     19237 non-null  str
 13  Drive wheels      19237 non-null  str
 14  Doors             19237 non-null  str
 15  Wheel             19237 non-null  str
 16  Color             19237 non-null  str
 17  Airbags           19237 non-null  int64
dtypes: int64(5), str(13)
memory usage: 2.6 MB

In [480]:
df.isnull().sum()

ID                  0
Price               0
Levy                0
Manufacturer        0
Model               0
Prod. year          0
Category            0
Leather interior    0
Fuel type           0
Engine volume       0
Mileage             0
Cylinders           0
Gear box type       0
Drive wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
dtype: int64

In [481]:
df = df.drop_duplicates()
df

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6,Automatic,4x4,4-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6,Tiptronic,4x4,4-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4,Variator,Front,4-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4,Automatic,4x4,4-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4,Automatic,Front,4-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,-,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000 km,4,Manual,Rear,2-Mar,Left wheel,Silver,5
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600 km,4,Tiptronic,Front,4-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365 km,4,Automatic,Front,4-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258 km,4,Automatic,Front,4-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923 km,4,Automatic,Front,4-May,Left wheel,White,12

In [482]:
df['Levy'] = df['Levy'].replace('-', np.nan)
df['Levy'] = df['Levy'].astype(float)

In [483]:
df.isnull().sum()

ID                     0
Price                  0
Levy                5709
Manufacturer           0
Model                  0
Prod. year             0
Category               0
Leather interior       0
Fuel type              0
Engine volume          0
Mileage                0
Cylinders              0
Gear box type          0
Drive wheels           0
Doors                  0
Wheel                  0
Color                  0
Airbags                0
dtype: int64

In [484]:
df['Mileage'] = df['Mileage'].str.replace(' km', '', regex=False)
df['Mileage'] = df['Mileage'].astype(int)

In [485]:
df['Turbo'] = df['Engine volume'].str.contains('Turbo').astype(int)
df['Engine volume'] = df['Engine volume'].str.replace(' Turbo', '', regex=False)
df['Engine volume'] = df['Engine volume'].astype(float)

In [486]:
df['Doors'] = df['Doors'].replace({
    '4-May': 4,
    '2-Mar': 2,
    '>5': 5
})
df['Doors'] = df['Doors'].astype(int)

In [487]:
df.select_dtypes(include='object').columns

C:\Users\GPC\AppData\Local\Temp\ipykernel_21376\3732952691.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns

Index(['Manufacturer', 'Model', 'Category', 'Leather interior', 'Fuel type',
       'Gear box type', 'Drive wheels', 'Wheel', 'Color'],
      dtype='str')

In [488]:
df = pd.get_dummies(df, columns=['Fuel type', 'Gear box type', 'Drive wheels', 'Wheel', 'Leather interior'], dtype=int)
df

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Engine volume,Mileage,Cylinders,...,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive,Leather interior_No,Leather interior_Yes
0,45654403,13328,1399.0,LEXUS,RX 450,2010,Jeep,3.5,186005,6,...,0,0,0,1,0,0,1,0,0,1
1,44731507,16621,1018.0,CHEVROLET,Equinox,2011,Jeep,3.0,192000,6,...,0,1,0,1,0,0,1,0,1,0
2,45774419,8467,NaN,HONDA,FIT,2006,Hatchback,1.3,200000,4,...,0,0,1,0,1,0,0,1,1,0
3,45769185,3607,862.0,FORD,Escape,2011,Jeep,2.5,168966,4,...,0,0,0,1,0,0,1,0,0,1
4,45809263,11726,446.0,HONDA,FIT,2014,Hatchback,1.3,91901,4,...,0,0,0,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,NaN,MERCEDES-BENZ,CLK 200,1999,Coupe,2.0,300000,4,...,1,0,0,0,0,1,1,0,0,1
19233,45778856,15681,831.0,HYUNDAI,Sonata,2011,Sedan,2.4,161600,4,...,0,1,0,0,1,0,1,0,0,1
19234,45804997,26108,836.0,HYUNDAI,Tucson,2010,Jeep,2.0,116365,4,...,0,0,0,0,1,0,1,0,0,1
19235,45793526,5331,1288.0,CHEVROLET,Captiva,2007,Jeep,2.0,51258,4,...,0,0,0,0,1,0,1,0,0,1
19236,45813273,470,753.0,HYUNDAI,Sonata,2012,Sedan,2.4,186923,4,...,0,0,0,0,1,0,1,0,0,1

In [489]:
df = df.drop('Model', axis=1)

label = LabelEncoder()

df['Manufacturer'] = label.fit_transform(df['Manufacturer'])
df['Category'] = label.fit_transform(df['Category'])
df['Color'] = label.fit_transform(df['Color'])

In [490]:
df['Levy'] = df['Levy'].fillna(df['Levy'].median())
df

,ID,Price,Levy,Manufacturer,Prod. year,Category,Engine volume,Mileage,Cylinders,Doors,...,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive,Leather interior_No,Leather interior_Yes
0,45654403,13328,1399.0,32,2010,4,3.5,186005,6,4,...,0,0,0,1,0,0,1,0,0,1
1,44731507,16621,1018.0,8,2011,4,3.0,192000,6,4,...,0,1,0,1,0,0,1,0,1,0
2,45774419,8467,781.0,21,2006,3,1.3,200000,4,4,...,0,0,1,0,1,0,0,1,1,0
3,45769185,3607,862.0,16,2011,4,2.5,168966,4,4,...,0,0,0,1,0,0,1,0,0,1
4,45809263,11726,446.0,21,2014,3,1.3,91901,4,4,...,0,0,0,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,781.0,36,1999,1,2.0,300000,4,2,...,1,0,0,0,0,1,1,0,0,1
19233,45778856,15681,831.0,23,2011,9,2.4,161600,4,4,...,0,1,0,0,1,0,1,0,0,1
19234,45804997,26108,836.0,23,2010,4,2.0,116365,4,4,...,0,0,0,0,1,0,1,0,0,1
19235,45793526,5331,1288.0,8,2007,4,2.0,51258,4,4,...,0,0,0,0,1,0,1,0,0,1
19236,45813273,470,753.0,23,2012,9,2.4,186923,4,4,...,0,0,0,0,1,0,1,0,0,1

In [491]:
X = df.drop(['Price', 'ID'], axis=1)
y = df['Price']

In [492]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [493]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [494]:
lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

LinearRegression()

In [495]:
y_pred_lr = lr.predict(X_test_scaled)
print("R²:", r2_score(y_test, y_pred_lr))

R²: -0.10584455276692473

In [496]:
knn = KNeighborsRegressor()
knn.fit(X_train_scaled, y_train)

KNeighborsRegressor()

In [497]:
y_pred_knn = knn.predict(X_test_scaled)
print("KNN R²:", r2_score(y_test, y_pred_knn))

KNN R²: -41.58259778469481

In [498]:
dt = DecisionTreeRegressor(random_state=42,max_depth=5,min_samples_leaf=5)
dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=5, min_samples_leaf=5, random_state=42)

In [499]:
y_pred_dt = dt.predict(X_test)
print("Decision Tree R²:", r2_score(y_test, y_pred_dt))

Decision Tree R²: -41.895475315380516

In [500]:
rf = RandomForestRegressor(random_state=42, n_estimators=100, max_depth=5, min_samples_leaf=5)
rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=5, min_samples_leaf=5, random_state=42)

In [501]:
y_pred_rf = rf.predict(X_test)
print("Random Forest R²:", r2_score(y_test, y_pred_rf))

Random Forest R²: -4.110899004875852

In [502]:
xgb = XGBRegressor(random_state=42)
xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [503]:
y_pred_xgb = xgb.predict(X_test)
print("XGBoost R²:", r2_score(y_test, y_pred_xgb))

XGBoost R²: -44.53863525390625

In [504]:
df['Price'].describe()

count    1.892400e+04
mean     1.858744e+04
std      1.921356e+05
min      1.000000e+00
25%      5.331000e+03
50%      1.317200e+04
75%      2.206300e+04
max      2.630750e+07
Name: Price, dtype: float64

In [505]:
def categorize(price):
    if price < 10000:
        return 'Low'
    elif price < 25000:
        return 'Medium'
    else:
        return 'High'

df['Price_Category'] = df['Price'].apply(categorize)

In [506]:
df['Price_Category'].value_counts()

Price_Category
Medium    7547
Low       7435
High      3942
Name: count, dtype: int64

In [507]:
X_cls = df.drop(['Price', 'ID', 'Price_Category'], axis=1)
y_cls = df['Price_Category']

In [508]:
X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(
    X_cls, y_cls, test_size=0.2, random_state=42, stratify=y_cls
)

In [509]:
scaler_cls = StandardScaler()
X_train_cls_scaled = scaler_cls.fit_transform(X_train_cls)
X_test_cls_scaled = scaler_cls.transform(X_test_cls)

In [510]:
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_cls_scaled, y_train_cls)
y_pred_log = log_reg.predict(X_test_cls_scaled)

print("Logistic Regression Accuracy:", accuracy_score(y_test_cls, y_pred_log))

Logistic Regression Accuracy: 0.6620871862615588

In [511]:
knn_cls = KNeighborsClassifier()
knn_cls.fit(X_train_cls_scaled, y_train_cls)
y_pred_knn_cls = knn_cls.predict(X_test_cls_scaled)

print("KNN Accuracy:", accuracy_score(y_test_cls, y_pred_knn_cls))

KNN Accuracy: 0.7899603698811096

In [512]:
dt_cls = DecisionTreeClassifier(random_state=42, max_depth=5, min_samples_leaf=5)
dt_cls.fit(X_train_cls, y_train_cls)
y_pred_dt_cls = dt_cls.predict(X_test_cls)
print("Decision Tree Accuracy:", accuracy_score(y_test_cls, y_pred_dt_cls))

Decision Tree Accuracy: 0.6932628797886393

In [513]:
rf_cls = RandomForestClassifier(random_state=42, n_estimators=100, max_depth=5, min_samples_leaf=5)
rf_cls.fit(X_train_cls, y_train_cls)
y_pred_rf_cls = rf_cls.predict(X_test_cls)
print("Random Forest Accuracy:", accuracy_score(y_test_cls, y_pred_rf_cls))

Random Forest Accuracy: 0.7365918097754294

In [514]:
le_target = LabelEncoder()
y_train_cls_enc = le_target.fit_transform(y_train_cls)
y_test_cls_enc = le_target.transform(y_test_cls)

xgb_cls = XGBClassifier(random_state=42)
xgb_cls.fit(X_train_cls, y_train_cls_enc)
y_pred_xgb_cls = xgb_cls.predict(X_test_cls)

print("XGBoost Accuracy:", accuracy_score(y_test_cls_enc, y_pred_xgb_cls))

XGBoost Accuracy: 0.8406869220607662